title: Crypto Mémoire
description: Les scams et projets douteux n’ont pas disparu ! Ils ont juste changé de forme.
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Compte X: https://x.com/GuruTanuki_
